# "handlers" can only run when "notify" task need to be changes, same "notify" are run in only one time.
# "changed_when" can make anready ran "ok" task status to Changed
# "failed_when" can make anready ran "ok" task status to Fail

--- 
- name: Simple Handler Example
  hosts: node01
  become: yes
  gather_facts: no
  tasks:
  - name: Creating Engineers Groups
    group:
      name: engineers
    notify: add elliot

  - name: One task in the play
    debug:
      msg: "Just One Task"
    changed_when: true
    notify: notify by debug

  - name: More task in the play
    debug:
      msg: "Just More Task"
    changed_when: true
    notify: notify by debug

  handlers:
    - name: add elliot
      user:
        name: elliot
        groups: engineers
        append: yes

    - name: notify by debug
      debug:
        msg: "Trigger for One and More tasks"
