- name: Allowing Ports
  become: true
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    firewall_ports:
      - 80
      - 81
      - 8080

  tasks:
    - name: allowing ports for server
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop: "{{ firewall_ports }}"
    

#      ansible.posix.firewalld:
#        port: 8080/tcp
#        permanent: yes
#        state: enabled
#        immediate: yes
