- name: Working with variables
  hosts: localhost
  #connection: local
  gather_facts: true
  become: false
  vars_files:
    - var-port-color.yaml
    - var-users.yaml

  tasks:
    - name: Show me fav_color value
      debug:
        msg: "My favorite color is {{ fav_color }}."

    - name: show me fav-color value again
      debug:
        msg: "{{ fav_color }} is my favorite color."
    
    - name: show port numbers
      debug:
        msg: "All the ports {{ port_nums }}"
  
    - name: showing First Port Number
      debug:
        msg: "First port number is {{ port_nums[0] }}"

    - name: showing both of users name
      debug:
        msg: "Users name are {{ users.bob.username }} and {{ users.lisa.username }}"

    - name: showing both of user id
      debug:
        msg: "Both of user id are {{ users['bob']['uid'] }}  and {{ users['lisa']['uid'] }}"

    - name: Checking Distrubution
      debug:
        msg: "{{ ansible_distribution }}"

    - name: Saving Gather Facts
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_yaml }}"
        dest: /tmp/ansible_facts
